#!/bin/bash
set -euo pipefail
source /etc/lobmob/env
source /etc/lobmob/secrets.env

# Derive WG subnet from lobboss's own WG address (e.g. 10.0.0.1 -> 10.0.0)
WG_SUBNET=$(ip -4 addr show wg0 2>/dev/null | grep -oP 'inet \K[0-9.]+' | rev | cut -d. -f2- | rev)
WG_SUBNET="${WG_SUBNET:-10.0.0}"

# Name generator — lobster-TYPE-NNN-adjective-name
# ~100 adjectives x ~100 water-themed character names
_ADJECTIVES=(salty briny bubbly soggy drippy splashy crusty sandy misty foamy breezy stormy slippery barnacled sunken rusty mossy silky shiny drifty tidal murky frothy ancient sunlit moonlit frozen steamy tropical arctic volcanic washed beached stranded marooned anchored capsized listing rolling pitching drifting cruising sailing surfing diving plunging sinking floating bobbing swaying rocking tumbling churning swirling rippling cresting breaking lapping ebbing flowing surging rushing gushing trickling dripping seeping wading paddling rowing sculling trawling tangled knotted braided coiled rigged masted keeled hulled planked craggy pearly abyssal coastal offshore inshore brackish saline brisk gusty balmy humid dewy hazy overcast squalling thundering howling whistling glassy choppy roiling frothing sparkling shimmering glistening gleaming luminous phosphorescent bioluminescent)
_NAMES=(squidward patrick sandy nemo dory marlin ariel flounder moana maui poseidon triton gilligan skipper wanda finn bubbles coral sheldon neptune aquaman mera namor calypso davy scylla amphitrite oceanus tethys nereus proteus glaucus lorelei undine sedna yemaya ryujin tangaroa ponyo ursula sebastian flotsam jetsam scuttle grimsby eric melody crush squirt bruce anchor chum gill bloat peach jacques gurgle deb nigel gerald hank destiny bailey becky fluke rudder smee hook wendy splash ripley darwin flipper willy shamu echo wahoo barracuda hammerhead stingray nautilus kraken leviathan jaws quint brody hooper ahab ishmael queequeg starbuck pip nessie selkie kelpie morgan drake kelvin marina oceana pearl reef cove fjord atoll lagoon estuary delta shoal caspian baltic coral anemone urchin abalone conch clam mussel oyster scallop starfish)
_gen_name() {
  local type="${1:-research}"
  local adj=${_ADJECTIVES[RANDOM % ${#_ADJECTIVES[@]}]}
  local name=${_NAMES[RANDOM % ${#_NAMES[@]}]}
  # Find lowest unused number among currently running lobsters
  local existing=$(doctl compute droplet list --tag-name "${LOBSTER_TAG}" --format Name --no-header 2>/dev/null)
  local num=1
  while echo "$existing" | grep -q "lobster-${type}-$(printf "%03d" $num)-" 2>/dev/null; do
    num=$((num + 1))
  done
  echo "${type}-$(printf "%03d" $num)-${adj}-${name}"
}
LOBSTER_TYPE="${3:-research}"
LOBSTER_ID="${1:-$(_gen_name $LOBSTER_TYPE)}"
WG_IP="${2:-}"

# SWE/QA lobsters need at least 2GB RAM (Opus model + dev tools OOM on 1GB)
SPAWN_SIZE="$LOBSTER_SIZE"
if [ "$LOBSTER_TYPE" = "swe" ] || [ "$LOBSTER_TYPE" = "qa" ]; then
  case "$SPAWN_SIZE" in
    s-1vcpu-1gb) SPAWN_SIZE="s-1vcpu-2gb" ;;
  esac
fi

if [ -z "$WG_IP" ]; then
  EXISTING=$(wg show wg0 allowed-ips 2>/dev/null | awk '{print $2}' | cut -d/ -f1 | sort -t. -k4 -n | tail -1)
  LAST_OCTET=$(echo "${EXISTING:-$WG_SUBNET.1}" | cut -d. -f4)
  NEXT_OCTET=$((LAST_OCTET + 1))
  WG_IP="$WG_SUBNET.${NEXT_OCTET}"
fi

# Read lobboss SSH public key for injecting into lobster authorized_keys
LOBBOSS_SSH_PUBKEY=$(cat /root/.ssh/lobster_admin.pub)

# Generate WireGuard keypair for lobster
LOBSTER_WG_PRIVKEY=$(wg genkey)
LOBSTER_WG_PUBKEY=$(echo "$LOBSTER_WG_PRIVKEY" | wg pubkey)
LOBBOSS_PUB_IP=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
LOBBOSS_WG_PUBKEY=$(wg show wg0 public-key)

# Build SECRET-FREE cloud-init for lobster
# Only contains: packages, WireGuard config (ephemeral key -- not a stored secret),
# SSH authorized keys, git identity, Node.js, OpenClaw, gh CLI install
LOBSTER_USERDATA=$(cat <<USERDATA
#!/bin/bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export HOME=/root
apt-get update
apt-get install -y wireguard git jq curl unzip

# Type-conditional packages
if [ "$LOBSTER_TYPE" = "swe" ] || [ "$LOBSTER_TYPE" = "qa" ]; then
  apt-get install -y build-essential shellcheck python3-pip
fi
if [ "$LOBSTER_TYPE" = "qa" ]; then
  pip3 install pytest --break-system-packages 2>/dev/null || pip3 install pytest
fi

# WireGuard -- uses ephemeral keypair generated by lobboss at spawn time
cat > /etc/wireguard/wg0.conf <<WGEOF
[Interface]
PrivateKey = $LOBSTER_WG_PRIVKEY
Address = $WG_IP/24
ListenPort = 51820

[Peer]
PublicKey = $LOBBOSS_WG_PUBKEY
AllowedIPs = $WG_SUBNET.0/24
Endpoint = $LOBBOSS_PUB_IP:51820
PersistentKeepalive = 25
WGEOF

wg-quick up wg0
systemctl enable wg-quick@wg0

# SSH authorized keys: DO metadata + lobboss admin key
mkdir -p /root/.ssh
curl -s http://169.254.169.254/metadata/v1/public-keys >> /root/.ssh/authorized_keys
printf '\n%s\n' "$LOBBOSS_SSH_PUBKEY" >> /root/.ssh/authorized_keys

# Git identity only -- no auth tokens
git config --global user.name "lobster-$LOBSTER_ID"
git config --global user.email "lobster-$LOBSTER_ID@lobmob.swarm"

# Install GitHub CLI (auth happens via lobboss SSH push)
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
  | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
  > /etc/apt/sources.list.d/github-cli.list
apt-get update && apt-get install -y gh

# Node.js 22
curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
apt-get install -y nodejs

# OpenClaw (config written later by lobboss via SSH)
npm install -g openclaw@latest
mkdir -p /root/.openclaw/skills /etc/lobmob

# Non-secret config
cat > /etc/lobmob/env <<ENVEOF
LOBSTER_ID=$LOBSTER_ID
WG_IP=$WG_IP
VAULT_REPO=$VAULT_REPO
LOBSTER_TYPE=$LOBSTER_TYPE
ENVEOF

# Event logger
cat > /usr/local/bin/lobmob-log <<'LOGEOF'
#!/bin/bash
CATEGORY="\$1"; shift
echo "\$(date -Iseconds) [\$CATEGORY] \$*" >> /var/log/lobmob-events.log
LOGEOF
chmod 755 /usr/local/bin/lobmob-log

# Flush event log to vault
cat > /usr/local/bin/lobmob-flush-logs <<'FLUSHEOF'
#!/bin/bash
set -euo pipefail

LOG_FILE="/var/log/lobmob-events.log"
VAULT_DIR="/opt/vault"
LOCK_FILE="/tmp/lobmob-flush.lock"

if [ ! -s "\$LOG_FILE" ]; then
  exit 0
fi

exec 200>"\$LOCK_FILE"
flock -n 200 || { echo "Another flush is running"; exit 0; }

if [ -f /etc/lobmob/env ]; then
  source /etc/lobmob/env
fi

if [ -n "\${LOBSTER_ID:-}" ]; then
  LOG_SUBDIR="020-logs/lobsters/lobster-\$LOBSTER_ID"
  COMMIT_PREFIX="[lobster-\$LOBSTER_ID]"
else
  LOG_SUBDIR="020-logs/lobboss"
  COMMIT_PREFIX="[lobboss]"
fi

TODAY=\$(date +%Y-%m-%d)
TARGET_FILE="\$VAULT_DIR/\$LOG_SUBDIR/events-\$TODAY.log"

cd "\$VAULT_DIR"
git pull origin main --quiet 2>/dev/null || true

mkdir -p "\$VAULT_DIR/\$LOG_SUBDIR"
cat "\$LOG_FILE" >> "\$TARGET_FILE"

git add "\$LOG_SUBDIR/"
if git diff --cached --quiet; then
  exit 0
fi

git commit -m "\$COMMIT_PREFIX Flush event log" --quiet
git push origin main --quiet

: > "\$LOG_FILE"
FLUSHEOF
chmod 755 /usr/local/bin/lobmob-flush-logs

# GitHub auth refresh -- regenerate App token and re-auth gh CLI
cat > /usr/local/bin/lobmob-refresh-gh-auth <<'GHREFRESHEOF'
#!/bin/bash
set -euo pipefail
if [ -f /etc/lobmob/env ]; then source /etc/lobmob/env; fi
TOKEN=""
if command -v lobmob-gh-token >/dev/null 2>&1; then
  TOKEN=$(lobmob-gh-token 2>/dev/null || true)
fi
if [ -z "$TOKEN" ]; then
  if [ -f /etc/lobmob/secrets.env ]; then
    source /etc/lobmob/secrets.env
    TOKEN="${GH_TOKEN:-}"
  fi
fi
if [ -z "$TOKEN" ]; then
  echo "ERROR: No GitHub token available" >&2
  exit 1
fi
echo "$TOKEN" | gh auth login --with-token 2>/dev/null
# Re-set git identity (gh auth setup-git clobbers .gitconfig)
if [ -n "${LOBSTER_ID:-}" ]; then
  git config --global user.name "lobster-$LOBSTER_ID"
  git config --global user.email "lobster-$LOBSTER_ID@lobmob.swarm"
else
  git config --global user.name "lobboss"
  git config --global user.email "lobboss@lobmob.swarm"
fi
echo "$(date -Iseconds) GitHub auth refreshed"
GHREFRESHEOF
chmod 755 /usr/local/bin/lobmob-refresh-gh-auth

# Flush cron -- every 15 minutes
echo "*/15 * * * * root /usr/local/bin/lobmob-flush-logs >> /var/log/lobmob-flush.log 2>&1" >> /etc/crontab

# GitHub auth refresh cron -- every 45 minutes
echo "*/45 * * * * root /usr/local/bin/lobmob-refresh-gh-auth >> /var/log/lobmob-gh-refresh.log 2>&1" >> /etc/crontab

# Systemd service for OpenClaw gateway (started after secrets provisioned)
cat > /etc/systemd/system/openclaw-gateway.service <<'SVCEOF'
[Unit]
Description=OpenClaw Gateway
After=network.target wg-quick@wg0.service
Wants=wg-quick@wg0.service

[Service]
Type=simple
WorkingDirectory=/opt/vault
EnvironmentFile=/root/.openclaw/.env
ExecStart=/usr/bin/env openclaw gateway --port 18789
Restart=on-failure
RestartSec=10
StandardOutput=append:/var/log/openclaw-gateway.log
StandardError=append:/var/log/openclaw-gateway.log

[Install]
WantedBy=multi-user.target
SVCEOF
systemctl daemon-reload

# Signal awaiting secrets
touch /etc/lobmob/.awaiting-secrets

# Log boot event
/usr/local/bin/lobmob-log boot "lobster-$LOBSTER_ID wg_ip=$WG_IP"

USERDATA
)

# Create the droplet
RESPONSE=$(doctl compute droplet create \
  "lobster-$LOBSTER_ID" \
  --region "$REGION" \
  --size "$SPAWN_SIZE" \
  --image ubuntu-24-04-x64 \
  --ssh-keys "$SSH_KEY_ID" \
  --vpc-uuid "$VPC_UUID" \
  --tag-name "$LOBSTER_TAG,${LOBSTER_TAG}-type-${LOBSTER_TYPE},${LOBSTER_TAG}-initializing" \
  --user-data "$LOBSTER_USERDATA" \
  --wait \
  --format ID,PublicIPv4 \
  --no-header \
  --output json)

DROPLET_ID=$(echo "$RESPONSE" | jq -r '.[0].id')
DROPLET_IP=$(echo "$RESPONSE" | jq -r '.[0].networks.v4[] | select(.type=="public") | .ip_address')

# Assign lobster to DO project
if [ -n "${DO_PROJECT_ID:-}" ]; then
  doctl projects resources assign "$DO_PROJECT_ID" --resource="do:droplet:$DROPLET_ID" 2>/dev/null || true
fi

# Add lobster as WireGuard peer on lobboss
wg set wg0 peer "$LOBSTER_WG_PUBKEY" allowed-ips "$WG_IP/32" endpoint "$DROPLET_IP:51820"

echo "Droplet created. Waiting for WireGuard connectivity..."
for i in $(seq 1 30); do
  if ping -c 1 -W 2 "$WG_IP" > /dev/null 2>&1; then
    echo "WireGuard: connected to $WG_IP"
    break
  fi
  sleep 5
done

# Wait for cloud-init to finish
echo "Waiting for cloud-init to complete on lobster..."

# Clear stale known_hosts first (WireGuard IPs get reused across spawns)
ssh-keygen -f /root/.ssh/known_hosts -R "$WG_IP" 2>/dev/null || true

# Poll for the .awaiting-secrets marker (last thing cloud-init writes)
for i in $(seq 1 60); do
  if ssh -i /root/.ssh/lobster_admin -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new \
    "root@$WG_IP" "test -f /etc/lobmob/.awaiting-secrets" 2>/dev/null; then
    echo "Cloud-init: done (marker found after $((i * 5))s)"
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "WARNING: cloud-init marker not found after 300s, proceeding anyway"
  fi
  sleep 5
done

# Push secrets to lobster via SSH over WireGuard
echo "Pushing secrets to lobster via SSH..."

# Write secrets.env
ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" "cat > /etc/lobmob/secrets.env && chmod 600 /etc/lobmob/secrets.env" <<SECRETS
GH_TOKEN=$GH_TOKEN
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
SECRETS

# Push GitHub App PEM and token script if configured
if [ -f /etc/lobmob/gh-app.pem ]; then
  scp -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new \
    /etc/lobmob/gh-app.pem "root@$WG_IP:/etc/lobmob/gh-app.pem"
  scp -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new \
    /usr/local/bin/lobmob-gh-token "root@$WG_IP:/usr/local/bin/lobmob-gh-token"
  ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" \
    "chmod 600 /etc/lobmob/gh-app.pem && chmod 755 /usr/local/bin/lobmob-gh-token"
  # Push App config to lobster env
  source /etc/lobmob/env
  ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" \
    "echo 'GH_APP_ID=${GH_APP_ID:-}' >> /etc/lobmob/env; echo 'GH_APP_INSTALL_ID=${GH_APP_INSTALL_ID:-}' >> /etc/lobmob/env"
fi

# Authenticate gh and clone vault
ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" bash <<PROVISION
set -euo pipefail
source /etc/lobmob/secrets.env

# GitHub auth (prefer App token, fall back to PAT)
GH_AUTH_TOKEN=""
if command -v lobmob-gh-token >/dev/null 2>&1; then
  GH_AUTH_TOKEN=\$(lobmob-gh-token 2>/dev/null || true)
fi
if [ -z "\$GH_AUTH_TOKEN" ]; then
  GH_AUTH_TOKEN="\$GH_TOKEN"
fi
echo "\$GH_AUTH_TOKEN" | gh auth login --with-token
gh auth setup-git
gh config set git_protocol https

# Re-set git identity (gh auth setup-git clobbers .gitconfig)
git config --global user.name "lobster-$LOBSTER_ID"
git config --global user.email "lobster-$LOBSTER_ID@lobmob.swarm"

# Clone vault
source /etc/lobmob/env
if [ -d /opt/vault ] && [ ! -d /opt/vault/.git ]; then rm -rf /opt/vault; fi
gh repo clone "$VAULT_REPO" /opt/vault 2>/dev/null || (cd /opt/vault && git stash 2>/dev/null; git pull origin main --rebase; git stash pop 2>/dev/null || true)
cd /opt/vault && git checkout main

# OpenClaw setup -- full automated configuration
mkdir -p /root/.openclaw/skills

# Step 1: Run openclaw onboard (creates openclaw.json)
# May hang over SSH -- timeout + || true handles this
timeout 30 openclaw onboard \
  --non-interactive --accept-risk --workspace /opt/vault 2>/dev/null || true

# Step 2: Create .env (API key loaded by gateway via EnvironmentFile)
echo "ANTHROPIC_API_KEY=\$ANTHROPIC_API_KEY" > /root/.openclaw/.env
chmod 600 /root/.openclaw/.env

# Step 3: Ensure openclaw.json exists (fallback if onboard hung)
if [ ! -f /root/.openclaw/openclaw.json ]; then
  GW_TOKEN=\$(openssl rand -hex 24)
  echo "{\"gateway\":{\"port\":18789,\"mode\":\"local\",\"bind\":\"loopback\",\"auth\":{\"mode\":\"token\",\"token\":\"\$GW_TOKEN\"}}}" > /root/.openclaw/openclaw.json
fi

# Step 4: Determine model and AGENTS.md based on lobster type
source /etc/lobmob/env
case "\$LOBSTER_TYPE" in
  swe) OC_MODEL="anthropic/claude-opus-4-6"; AGENTS_MODEL="anthropic:claude-opus-4-6-20250918" ;;
  qa)  OC_MODEL="anthropic/claude-sonnet-4-5"; AGENTS_MODEL="anthropic:claude-sonnet-4-5-20250929" ;;
  *)   OC_MODEL="anthropic/claude-sonnet-4-5"; AGENTS_MODEL="anthropic:claude-sonnet-4-5-20250929" ;;
esac

# Step 5: Patch openclaw.json with Discord channels + agent config
# Note: don't include gateway block -- openclaw onboard already sets it with auth token
jq --arg token "\$DISCORD_BOT_TOKEN" --arg model "\$OC_MODEL" '{
  channels: { discord: { enabled: true, token: \$token, groupPolicy: "allowlist",
    guilds: { "467002962456084481": { slug: "mattcave", requireMention: false,
reactionNotifications: "own",
channels: { "'"${DISCORD_CHANNEL_TASK_QUEUE:-task-queue}"'": {allow:true}, "'"${DISCORD_CHANNEL_SWARM_CONTROL:-swarm-control}"'": {allow:true}, "'"${DISCORD_CHANNEL_SWARM_LOGS:-swarm-logs}"'": {allow:true} }
    }}
  }},
  agents: { defaults: { model: { primary: \$model }, workspace: "/opt/vault" }}
} * .' /root/.openclaw/openclaw.json > /tmp/oc.tmp && mv /tmp/oc.tmp /root/.openclaw/openclaw.json

# Step 6: Remove old config.json if it exists (superseded by openclaw.json)
rm -f /root/.openclaw/config.json

# Step 7: Copy lobster skills from vault (type-specific)
# Base skills (all types)
for skill in vault-read vault-write submit-results; do
  cp -r "/opt/vault/040-fleet/lobster-skills/\$skill" /root/.openclaw/skills/ 2>/dev/null || true
done
# Type-specific skills
case "\$LOBSTER_TYPE" in
  swe)      cp -r /opt/vault/040-fleet/lobster-skills/code-task /root/.openclaw/skills/ 2>/dev/null || true ;;
  qa)       cp -r /opt/vault/040-fleet/lobster-skills/verify-task /root/.openclaw/skills/ 2>/dev/null || true ;;
  research) cp -r /opt/vault/040-fleet/lobster-skills/task-execute /root/.openclaw/skills/ 2>/dev/null || true ;;
  *)        cp -r /opt/vault/040-fleet/lobster-skills/task-execute /root/.openclaw/skills/ 2>/dev/null || true ;;
esac

# Step 8: Clone target repo for SWE/QA lobsters
if [ "\$LOBSTER_TYPE" = "swe" ] || [ "\$LOBSTER_TYPE" = "qa" ]; then
  gh repo clone minsley/lobmob /opt/lobmob 2>/dev/null || (cd /opt/lobmob && git pull origin develop --rebase 2>/dev/null || true)
  cd /opt/lobmob && git checkout develop 2>/dev/null || git checkout -b develop origin/develop 2>/dev/null || true
fi

# Step 9: Write lobster AGENTS.md (metadata only -- system prompt comes from vault)
cat > /root/.openclaw/AGENTS.md <<AGENTEOF
---
name: lobster-$LOBSTER_ID
type: $LOBSTER_TYPE
model: \$AGENTS_MODEL
---
AGENTEOF

# Step 8: Start gateway via systemd
systemctl enable openclaw-gateway
systemctl start openclaw-gateway

# Mark secrets provisioned
rm -f /etc/lobmob/.awaiting-secrets
echo "LOBSTER_READY"
PROVISION

echo "Lobster provisioned."

# Log ready event on the lobster
ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" \
  "lobmob-log ready lobster-$LOBSTER_ID" 2>/dev/null || true

# Write config version to lobster for pool management staleness checks
CONFIG_VERSION=$(md5sum /usr/local/bin/lobmob-spawn-lobster | awk '{print $1}')
ssh -i /root/.ssh/lobster_admin -o StrictHostKeyChecking=accept-new "root@$WG_IP" \
  "echo '$CONFIG_VERSION' > /etc/lobmob/config-version"

# Transition from initializing -> active (swap tags)
doctl compute droplet tag "$DROPLET_ID" --tag-name "${LOBSTER_TAG}-active" 2>/dev/null || true
doctl compute droplet untag "$DROPLET_ID" --tag-name "${LOBSTER_TAG}-initializing" 2>/dev/null || true

lobmob-log spawn "lobster-$LOBSTER_ID type=$LOBSTER_TYPE droplet=$DROPLET_ID wg_ip=$WG_IP"

# Output lobster info as JSON
cat <<EOF
{
  "lobster_id": "lobster-$LOBSTER_ID",
  "type": "$LOBSTER_TYPE",
  "droplet_id": "$DROPLET_ID",
  "public_ip": "$DROPLET_IP",
  "wireguard_ip": "$WG_IP",
  "wg_public_key": "$LOBSTER_WG_PUBKEY"
}
EOF
