# lobmob setup — interactive bootstrap wizard
# Usage: lobmob setup

prompt_yn() {
  local prompt="$1" default="${2:-y}"
  if [[ "$default" == "y" ]]; then
    read -rp "$(echo -e "${CYAN}[lobmob]${NC} ${prompt} [Y/n] ")" answer
    [[ ! "$answer" =~ ^[nN] ]]
  else
    read -rp "$(echo -e "${CYAN}[lobmob]${NC} ${prompt} [y/N] ")" answer
    [[ "$answer" =~ ^[yY] ]]
  fi
}

prompt_value() {
  local prompt="$1" var_name="$2" default="${3:-}"
  local current="${!var_name:-$default}"
  if [[ -n "$current" ]]; then
    read -rp "$(echo -e "${CYAN}[lobmob]${NC} ${prompt} [${current}]: ")" value
    value="${value:-$current}"
  else
    read -rp "$(echo -e "${CYAN}[lobmob]${NC} ${prompt}: ")" value
  fi
  eval "$var_name=\"\$value\""
}

log "lobmob setup wizard ($LOBMOB_ENV environment)"
echo ""

# Load existing secrets if available
if [[ -f "$SECRETS_FILE" ]]; then
  log "Found existing secrets file: $SECRETS_FILE"
  set -a; source "$SECRETS_FILE" 2>/dev/null || true; set +a
fi

# ── Stage 1: Prerequisites ───────────────────────────────────────────
log "Checking prerequisites..."
MISSING=()
for cmd in terraform kubectl docker jq curl python3; do
  if command -v "$cmd" &>/dev/null; then
    log "  $cmd: $(command -v "$cmd")"
  else
    warn "  $cmd: NOT FOUND"
    MISSING+=("$cmd")
  fi
done

# gh is optional (used for vault-init and PR management)
if command -v gh &>/dev/null; then
  log "  gh: $(command -v gh)"
else
  warn "  gh: NOT FOUND (optional, install with: brew install gh)"
fi

if [[ ${#MISSING[@]} -gt 0 ]]; then
  err "Missing required tools: ${MISSING[*]}"
  err "Install them and re-run lobmob setup"
  exit 1
fi
echo ""

# ── Stage 2: DigitalOcean ────────────────────────────────────────────
if prompt_yn "Configure DigitalOcean API token?"; then
  prompt_value "DO API token" DO_TOKEN
  log "Validating token..."
  ACCOUNT=$(curl -sf -H "Authorization: Bearer $DO_TOKEN" \
    "https://api.digitalocean.com/v2/account" 2>/dev/null | jq -r '.account.email // empty')
  if [[ -n "$ACCOUNT" ]]; then
    log "  Authenticated as: $ACCOUNT"
  else
    warn "  Token validation failed — continuing anyway"
  fi
  echo ""
fi

# ── Stage 3: Anthropic ───────────────────────────────────────────────
if prompt_yn "Configure Anthropic API key?"; then
  prompt_value "Anthropic API key" ANTHROPIC_API_KEY
  echo ""
fi

# ── Stage 4: Discord ─────────────────────────────────────────────────
if prompt_yn "Configure Discord bot?"; then
  prompt_value "Discord bot token" DISCORD_BOT_TOKEN
  echo ""
fi

# ── Stage 5: Gemini (optional) ───────────────────────────────────────
if prompt_yn "Configure Gemini API key (optional, for image-gen lobsters)?" "n"; then
  prompt_value "Gemini API key" GEMINI_API_KEY
  echo ""
fi

# ── Stage 6: GitHub ──────────────────────────────────────────────────
if prompt_yn "Configure GitHub access?"; then
  prompt_value "GitHub PAT (for lobboss vault access)" GH_TOKEN

  if prompt_yn "Create a GitHub App for the token broker?"; then
    echo ""
    source "$SCRIPT_DIR/commands/setup-github.sh"
    # Reload secrets after setup-github writes them
    set -a; source "$SECRETS_FILE" 2>/dev/null || true; set +a
  else
    if prompt_yn "Enter existing GitHub App credentials?" "n"; then
      prompt_value "GitHub App ID" GH_APP_ID
      prompt_value "GitHub App Install ID" GH_APP_INSTALL_ID
      prompt_value "GitHub App PEM (base64)" GH_APP_PEM
    fi
  fi
  echo ""
fi

# ── Stage 7: Write secrets file ──────────────────────────────────────
log "Writing secrets to ${SECRETS_FILE}..."

cat > "$SECRETS_FILE" <<SECRETS_EOF
# lobmob secrets ($LOBMOB_ENV) — generated by lobmob setup
# NEVER commit this file — it is gitignored.

DO_TOKEN=${DO_TOKEN:-}
GH_TOKEN=${GH_TOKEN:-}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}

# GitHub App (token broker)
GH_APP_ID=${GH_APP_ID:-}
GH_APP_INSTALL_ID=${GH_APP_INSTALL_ID:-}
GH_APP_PEM=${GH_APP_PEM:-}
SECRETS_EOF

log "Secrets written to $SECRETS_FILE"
echo ""

# ── Stage 8: Push to k8s ─────────────────────────────────────────────
if prompt_yn "Push secrets to k8s cluster now?"; then
  LOBMOB_ENV="$LOBMOB_ENV" "$SCRIPT_DIR/../lobmob" secrets push

  if [[ -n "${GH_APP_ID:-}" && -n "${GH_APP_PEM:-}" ]]; then
    if prompt_yn "Also push broker secrets (lobwife-secrets)?"; then
      LOBMOB_ENV="$LOBMOB_ENV" "$SCRIPT_DIR/../lobmob" secrets push-broker
    fi
  fi
  echo ""
fi

log "Setup complete!"
log ""
log "Next steps:"
log "  1. Deploy infrastructure:  lobmob deploy"
log "  2. Check status:           lobmob status"
log "  3. Verify:                 lobmob verify all"
